### ISSUE TITLE
Layout problems with Atom Material UI

### ISSUE THREAD

**Issue by pogramos** [benjaminRomano/gulp-manager#13]
The control bar isn't shown while using Atom Material UI, it works well with One Light/Dark UI.

**## Atom Material**
![captura de tela 2016-06-09 as 18 19 12](https://cloud.githubusercontent.com/assets/15428949/15946774/b4a4fcb6-2e6e-11e6-866f-c6de9d285a92.png)

**## One Light**
![captura de tela 2016-06-09 as 18 18 32](https://cloud.githubusercontent.com/assets/15428949/15946759/9e28965a-2e6e-11e6-9ba5-383a4c8c9824.png)

**Comment by benjaminRomano** [comment]
This is a problem with bottom-dock. 
I've opened an issue here https://github.com/benjaminRomano/bottom-dock/issues/13 and I'll take a look at it when I get a chance

I'm closing this one for now.
