### ISSUE TITLE
Gulp Manager not compatible with One Light UI

### ISSUE THREAD

**Issue by perez-rich** [benjaminRomano/gulp-manager#2]
This is pretty simple to reproduce.
1. Change your theme to One Light
2. Open up Gulp Manager
3. Run any task
4. ????
5. Profit!

Actually, you can't read any text except for the time and the task that ran. If you change to a dark theme you can read it pretty well. I took a look at the source it looks like you're hardcoding to #fff. Maybe move that to a stylesheet and use one of the theme variables so it can adjust properly?

**Comment by benjaminRomano** [comment]
I pushed out a new version (0.2.10). Can you verify that this fixes the problem for you. Thanks

**Comment by perez-rich** [comment]
Yup that fixed it. Thanks for the quick reply!
