### ISSUE TITLE
Custom Task input visibility and scrolling in output problem

### ISSUE THREAD

**Issue by opus1269** [benjaminRomano/gulp-manager#5]
Hate to say it, but the latest Atom update broke this again. One thing I noticed is that it happens when the output text is long enough to require the scrollbar to become visible, and clearing the output corrects it. Also the last line or two of the output is not visible when scrolled.

I have switched to gulp (finally) but it is an issue with grunt-manager too.

**Comment by benjaminRomano** [comment]
Should be fixed by 051004ff6f8078f6e006e022e1236683b17b834e in v0.2.17.

Also, I fixed the problem in grunt-manager in v0.1.15. 

All this flex-box stuff get so confusing :confused:

**Comment by opus1269** [comment]
gulp is good, can't test grunt right now.

I use Polymer, they have a wrapper for flexbox that makes it pretty nice to work with.
