### ISSUE TITLE
Garbled

### ISSUE THREAD

**Issue by springeye** [benjaminRomano/gulp-manager#6]
fetching gulp tasks for gulpfile.js
'gulp' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Exited with code 1

**Comment by benjaminRomano** [comment]
What OS are you running on? 
Also, verify that gulp is installed either locally or globally.

Lastly, if possible can you post the gulpfile you are using.

**Comment by springeye** [comment]
@benjaminRomano https://github.com/henjue/vue-bootstrap/blob/master/gulpfile.js

**Comment by springeye** [comment]
@benjaminRomano 
windows 10 and mac os 
Chinese

**Comment by benjaminRomano** [comment]
Can you post the output of gulp --tasks.

I'm guessing the package I use to convert terminal output to html (ansi-to-html) doesn't support Chinese characters.  I'll try and fix this over the weekend
