### ISSUE TITLE
Custom keymap not working

### ISSUE THREAD

**Issue by benfrain** [benjaminRomano/gulp-manager#8]
First, thanks for this plugin. It's really great and makes Atom palatable for me :+1: 

I have a tiny issue. I have unticked the 'Enable' under keystrokes in the Gulp Manager settings and added this to my keystrokes file:

```
'atom-workspace':
  'ctrl-y': 'gulp-manager:toggle'
```

However, the binding doesn't toggle the panel. Am I doing something obviously wrong (new Atom user, so quite possible).

I have tried with the tick box checked too but the same result. The original binding of

**Comment by benjaminRomano** [comment]
You'll want to use this since bottom-dock handles the toggling.

``` js
'atom-workspace':
  'ctrl-y': 'bottom-dock:toggle'
```

**Comment by benfrain** [comment]
Ah, brilliant, thanks. And thanks for Gulp Manager :+1:
